Fix: missing argument
This fixes run.py problem:

Traceback (most recent call last):
  File "run.py", line 536, in <module>
    elif args.delete_obsolete:
AttributeError: 'Namespace' object has no attribute 'delete_obsolete'